--TRIGGERS--
-- CATEGORIE CARACTERISTI--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM CATEGORIE_CARACTERISTICI;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE CATEGORIE_CARACT_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CATEGORIE_CARACT_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_CATEG_CARACT
BEFORE INSERT ON CATEGORIE_CARACTERISTICI
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  CATEGORIE_CARACT_ID.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/

--USERS--

DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM USERS;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE USERS_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_USERS
BEFORE INSERT ON USERS
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  USERS_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/

--MEDIA--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM MEDIA;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE MEDIA_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE MEDIA_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_MEDIA
BEFORE INSERT ON MEDIA
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  MEDIA_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/

--USERS HATES--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM USER_HATES;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE USER_HATES_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE USER_HATES_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_USER_HATES
BEFORE INSERT ON USER_HATES
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  USER_HATES_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/
--USER LOVES--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM USER_LOVES;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE USER_LOVES_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE USER_LOVES_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_USER_LOVES
BEFORE INSERT ON USER_LOVES
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  USER_LOVES_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/
--PRODUS--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM PRODUS;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUS_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE PRODUS_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_PRODUS
BEFORE INSERT ON PRODUS
FOR EACH ROW
BEGIN
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
      Select  PRODUS_ID_SEQ.NEXTVAL
      INTO    :new.id
      FROM    dual;
   END IF;
END;
/
--CARACTERISTICA--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM CARACTERISTICA;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE CARACTERISTICA_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CARACTERISTICA_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_CARACTERISTICA
BEFORE INSERT ON CARACTERISTICA
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  CARACTERISTICA_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/
--CARACTERISTICI PRODUSE--
DECLARE
 last_index NUMBER;
BEGIN
  SELECT MAX(ID)+ 1 INTO last_index FROM CARACTERISTICI_PRODUSE;
  IF last_index > 0 THEN
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE CARACTERISTICI_PRODUSE_ID_SEQ';
      EXCEPTION WHEN OTHERS THEN
        NULL;
    END;
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CARACTERISTICI_PRODUSE_ID_SEQ INCREMENT BY 1 START WITH ' || last_index || ' CACHE 50 NOMAXVALUE NOCYCLE';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER AI_CARACT_PROD
BEFORE INSERT ON CARACTERISTICI_PRODUSE
FOR EACH ROW

BEGIN 
    IF :new.id IS NULL THEN --in case we have an id when we insert (eg when importing from csv) we do not use the trigger
    Select  CARACTERISTICI_PRODUSE_ID_SEQ.NEXTVAL
    INTO    :new.id
    FROM    dual;
    END IF;
END;
/

